services:
#maria-db
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    build: ./src/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./src/.env
    environment:
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks :
      - inception
    restart : always
#nginx
  nginx:
    image: nginx:user
    container_name: nignx
    build: ./src/nginx
    ports:
      - "4433:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./src/wordpress
    depends_on:
      -  mariadb
    volumes:
      -  wordpress:/var/www/wordpress
    env_file:
      - ./src/.env
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mohilali/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver : local
    driver_opts:
      device: /home/mohilali/data/wordpress
      o : bind
      type: none

networks :
  inception:
    name: inception
