services:
#maria-db
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./src/mariadb
    volumes:
      - mariadbv:/var/lib/mysql
    env_file:
      - ./src/.env
    networks :
      - inception
    restart : always
#nginx
  nginx:
    image: nginx:user
    container_name: nignx
    build: ./src/nginx
    ports:
      - "4433:443"
    depends_on:
      - wordpress
    volumes:
      - wordpressv:/var/www/wordpress
    networks:
      - inception
    restart: always
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./src/wordpress
    depends_on:
      -  mariadb
    volumes:
      -  wordpressv:/var/www/wordpress
    env_file:
      - ./src/.env
    networks:
      - inception
    restart: always

volumes:
  mariadbv:
  wordpressv:

networks :
  inception:
    name: inception
