
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "3306:3306"
    secrets:
      - db_user_password
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "9000:9000"
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_user_password
    restart: always

  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    restart: always
  
  redis:
    image: redis
    container_name: redis
    build : ./requirements/bonus/redis
    volumes:
      - wordpress_v:/var/www/html
    restart: always
    networks:
      - inception

  ftp:
    image: ftp
    container_name: ftp
    build: ./requirements/bonus/FTP
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - ./.env
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    secrets:
      - ft_user_password
    restart: always



  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/Adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always


  static_site:
    image: static_site
    container_name: static_website
    build: ./requirements/bonus/static_website
    ports:
      - "8000:8000"
    networks:
      - inception
    restart: always

  prometheus:
    build: ./requirements/bonus/pro-grafana/prometheus
    image: prometheus:latest
    container_name: prometheus
    volumes:
      -  prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - inception
    restart: always

  grafana:
    build: ./requirements/bonus/pro-grafana/grafana
    image: custom-grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - inception
    restart: always

  cadvisor:
    image: cadvisor
    build: ./requirements/bonus/pro-grafana/cadvisor
    container_name: cadvisor
    ports:
      - "4040:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  mariadb_v:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/mariadb"
  wordpress_v:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress"
  grafana_data:
  prometheus_data:

secrets:
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ft_user_password:
    file: ../secrets/ft_user_password.txt

networks:
  inception:
    driver: bridge

