
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_v:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_v:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "9000:9000"
    restart: always

  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    restart: always
  
  redis:
    image: redis
    container_name: redis
    build : ./requirements/bonus/redis
    volumes:
      - wordpress_v:/var/www/html
    restart: always
    networks:
      - inception

  ftp:
    image: ftp
    container_name: ftp
    build: ./requirements/bonus/FTP
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - ./.env
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    restart: always



  adminer:
    image: adminer
    container_name: adminer
    build: ./requirements/bonus/Adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always


  static_site:
    image: static_site
    container_name: static_website
    build: ./requirements/bonus/static_website
    ports:
      - "8000:8000"
    networks:
      - inception
    restart: always

  prometheus:
    build:
      context: ./requirements/bonus/pro-grafa/prometheus
    image: custom-prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - inception
    restart: always

  grafana:
    build:
      context: ./requirements/bonus/pro-grafa/grafana
    image: custom-grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - inception
    restart: always
 
volumes:
  mariadb_v:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/mariadb"
  wordpress_v:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress"
  grafana_data:
  prometheus_data:

networks:
  inception:
    driver: bridge

